### ISSUE TITLE
Tune "Try mode"

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1153]
Este tam chyba par veci:

- [x] Fix podmienok zobrazovania: #1151, #1152 a 756354148e9670e2b5edcbf063865479b9d7b425
- [x] Feedback od Hanky
- [x] Fix rozostreneho modalu
- [x] Fix warningov: ce63555
- [x] Fix obrazkov, asi maju zlu cestu a nenacitavaju sa (v produkcii)
- [x] Povolit iframe s youtube videom: https://github.com/keboola/connection/pull/1000
- [x] Fix hover "Settings -> Try mode" (asi by malo byt `color: #fff`
- [x] Vyhodit staru `try-mode` route: #1154 
- [x] Fixnut prechod na "Storage" #1243 
- [x] 1366 respo fix

**Comment by ujovlado** [comment]
Ten rozostreny modal vyzera takto:
![screenshot_2017-09-20_13-36-46](https://user-images.githubusercontent.com/419849/30641847-cfd5ed78-9e08-11e7-925f-1ead50dc857a.png)

moze za to css `transform: translate(50%, -50%);`, bude to treba fixnut

**Comment by ujovlado** [comment]
Spominany hover:
![screenshot_2017-09-20_14-22-34](https://user-images.githubusercontent.com/419849/30643449-3aa6202c-9e0f-11e7-93cc-617f58fb2480.png)

**Comment by ujovlado** [comment]
Este tam nefunguje prechod na "Storage"

**Comment by odinuv** [comment]
1366x768 Neni videt applications a neni tam scroll:
![clipboard01](https://user-images.githubusercontent.com/4319320/30645373-dabf27d8-9e15-11e7-9c17-712a81eed1ac.png)

**Comment by janmichek** [comment]
ok, prijimam, opravim

**Comment by janmichek** [comment]
fajnovy, domnivam se ze jsem to opravil spravne. Neco nezbyva nez to vyzkouset v produkci. Nasadim tedy a pak se dostanu k tem dalsim zalezitostem + texty.

**Comment by janmichek** [comment]
Kdyby mi nekdo dokazal pomoct nebo poradit s timhle:  Fixnut prechod na "Storage", budu moc rad. Nemuzu prijit na to jak je spravne ta routa. Me nezbyva nez to zkouset na produkci. Ten link neni 'storage' ani '/storage' ani '//storage'

**Comment by Halama** [comment]
storage je uplne separatni appka, link na ni udelas jako `storage`. Kazdopadne try mode tam nepojede.

**Comment by Halama** [comment]
Na vygenerovani linku slouží tohle https://github.com/keboola/kbc-ui/blob/7b7b86345a868740acb70f37e052e202e5273cac/src/scripts/stores/ApplicationStore.coffee#L78 zavolané jako `getProjectPageUrl('storage')`

**Comment by janmichek** [comment]
Diky za radu, zkusim to. Za me dost znepokojujici zprava xD

**Comment by ujovlado** [comment]
Tu to zavrem, hore v issue je uz vsetko vyriesene (prechod na storage ma separatny PR)
