### ISSUE TITLE
Tune guide mode part6

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1318]
- Dobrá zpráva - guide mode už nehlásí žádný errory v Sentry. 
Snažil jsem se projet guide-mode jako BFU. Pokud neco chybi, nevahejte dopsat.
Tady jsou moje postrehy, racte si rozebrat:

---
**Jan**
- [x] predat k user testum

**Vlado**
- [x] 'Prev step' se ted chova jinak nez predtim. Vraci to o vic kroku. Potom se rozjede navigace / routovani [L2 - L5] // presiel som to, funguje to ok.

**DONE**
- [x] opdovedet Hance - Jak prosim te bude fungovat konec L4 Visualizing Results? Bude mozny se podivat na ten soubor ve Storage? Budou si ten soubor lidi moct stahnout na svuj pocitac?
- [x] zkusit okno s instrukcemi udelat vertikalne na celou obrazovku (zase - usetrilo by to misto pro text a nebyl by nutny scroll bar) // okno zvetseno, na minimalnim rozliseni 1366x768 zabira max vysku
- [x] prekryv modalu 3.4 (nejde posouvat instrukce, neni mozny kopirovat texty z instrukci)
- [x] 3.4 upravit spravne sql kod cars vs CARS
- [x] check dvojmezery v produkci na 3.4
- [x] 2.5 -> 2.6 - otextovat klik na next step
- [x] L4 konec byl rozdelen na 2 stepy. Prosim o upravu txtu

- [x] 4.3 - ' you want to add to' tady se nabizi slovo 'select' misto 'add', klikam totiz na 'Select' 
- [x] 5.4 - klik na 'Save', navigovat uzivatele textem
- [x] 3.5 -> 3.6 - Popisek 'You can check ...' muze byt direktivnejsi.
- [x] 2.6 -> trochu jsem se ztratil v textu. 'If you open ...' otevrelo se mi to ale automaticky. 'bucket in.c-keboola-ex-db-snowflake' chvilku jsem hledal ze je to vlevo a co mam udelat.
- [x] texty - vsiml jsem si nekonzistentniho stylovani textu - kurziva, bold, <code></code>. Nekdy ma styl vic vyznamu, nebo naopak
- [x] nice to have - vizualne lepsi prechody (trhane, next/prev step)
- [x] 4.4 - bude potreba rozdelit na 2 stepy. Text s obrazky se nevejde do modalu. Nevejde se teda ani samotny obrazek xD budu to muset trochu pophotoshopit. Optimalizujem na 1366 x 768.
- [x] 5.4 - klik na 'Save' me predtim hodil na detail orchestrace, coz bylo fajn. POkud to nemuzem obnovit, je potreba navigovat uzivatele textem. // vid. https://github.com/keboola/kbc-ui/issues/1318#issuecomment-347235032
- [x] poslední step je v každý lekci jiny =  navrhuju vyhodit 'Lesson 3 Finished' nebo podobne
- [x] 3.5 -> 3.6 - po kliku na 'Run extraction' by bylo fajn routnout na Jobs. Popisek 'You can check ...' muze byt direktivnejsi. // hotovo: https://github.com/keboola/kbc-ui/issues/1318#issuecomment-347192208 a fix v 0953242805c8305550ae122834aeb8150570fa2e
- [x] po ukonceni druhy lekce se neodemkne 3.leckce. Je potreba reloadnout. // fixed in #1317 
- [x]  4.2 -> hodil by se link na Tableau desktop, kdyby tu appku treba nekdo nemel.
- [x] vytunit 'Buttonlike' featuru. Pripada mi to nazorne, ale vadi mi to maly pismo. Pokud se rozhodnem to pouzit, potom je potreba nektery minitlacitka obarvit prislusnou barvou - ted to nesedi.

**Comment by janmichek** [comment]
resim -> poslední step je v každý lekci jiny = navrhuju vyhodit 'Lesson 3 Finished' nebo podobne

**Comment by ujovlado** [comment]
> po ukonceni druhy lekce se neodemkne 3.leckce. Je potreba reloadnout.

toto sa myslim fixlo prave v https://github.com/keboola/kbc-ui/pull/1317 mozes to skusit este raz?

**Comment by ujovlado** [comment]
Este upravit CSSka, pri kombinacii s inymi "overview" komponentami to je trosku rozbite:

![screenshot_2017-11-27_13-48-39](https://user-images.githubusercontent.com/419849/33269767-2103493a-d382-11e7-82ec-68ab3bf27d3e.png)

**Comment by ujovlado** [comment]
> 3.5 -> 3.6 - po kliku na 'Run extraction' by bylo fajn routnout na Jobs. Popisek 'You can check ...' muze byt direktivnejsi.

vyhodim automaticku zmenu v modale, routne sa to po kliknu na next step.

**Comment by janmichek** [comment]
tu stylovacku poresim, pripisuju.
Potvrzuju ze jsi to fixnul v #1317.  Ted tam vidim ze je o jeden step navic. 3.7. se zobrazi 2x, jen tak to problikne. Zvlastni je ze se to na devu nedeje, tam to funguje dle ocekavani.

**Comment by ujovlado** [comment]
> 5.4 - klik na 'Save' me predtim hodil na detail orchestrace, coz bylo fajn. POkud to nemuzem obnovit, je potreba navigovat uzivatele textem.

toto som spominal uz na Slacku, bude potrebne doriesit textom. oznacujem ako done.

**Comment by janmichek** [comment]
Ok, radeji to prehazuju na Hanku. Presmahnul jsi mi zmeny v puvodnim komentari s tuduckem.

**Comment by janmichek** [comment]
@ujovlado

**Comment by ujovlado** [comment]
> Ok, radeji to prehazuju na Hanku. Presmahnul jsi mi zmeny v puvodnim komentari s tuduckem.

stlacil som checkbox a po ulozeni komentara https://github.com/keboola/kbc-ui/issues/1318#issuecomment-347235032 sa mi to reloadlo a videl som tam o5 to stare (asi nejaky ajax call ... nie je dovod aby som ti prepisoval komentare ;))

... ak mi teda davas mention kvoli tomu @janmichek

**Comment by janmichek** [comment]
cekal bych od tebe neco jako: 'ups, to me mrzi'. Nevadi, predelam to znova.

**Comment by ujovlado** [comment]
ja by som zase cakal, ze taketo picoviny nebudeme riesit ;) ... z toho co som si stihol vsimnut, tam zmizli 4 nadpisy ... ak mas pocit, ze ti tam zmizlo nieco velke, da sa to imho vytiahnut z API githubu

**Comment by janmichek** [comment]
no comment

**Comment by ujovlado** [comment]
@janmichek Este som sa hrabal v "Automation" a je tam maly bug:
![screenshot_2017-11-29_17-49-41](https://user-images.githubusercontent.com/419849/33387586-f67275a8-d52d-11e7-9a35-f515e41f4496.png)

Vyzera, ze je to tym, ze je to ako tabulka. Mozno by sa to mohlo solvnut cez row a col (aby sa pri mensom rozlisku dali pod seba)

**Comment by ujovlado** [comment]
@janmichek toto by si mohol rozviest?

> 'Prev step' se ted chova jinak nez predtim. Vraci to o vic kroku. Potom se rozjede navigace / routovani [L2 - L5]

Nemenil som na tom chovani imho nic. Co znamena "Vraci to o vic kroku"?

**Comment by janmichek** [comment]
@ujovlado ted koukam ze to dela ruzny veci. Zkus si dat nejakou lekci L2 - L5 a vratit se o par kroku pomoci Prev a pak zase nazpet pomoci Next. Neroutuje to uplne spolehlive

**Comment by ujovlado** [comment]
imho zalezi ako rychlo klikas ... ak vzdy pockas, sprava sa to ok ... ak klikas "fast & furious", tak medzi prechodom storage-console<->kbc-ui to moze zblbnut ... a to asi nemame ako ovplyvnit.

**Comment by janmichek** [comment]
@ujovlado nemyslim si ze je to jenom tim. Zkus tohle: Nasleduju vsechny instrukce, proklikam se k 2.5 -> kliknu Prev -> nic se nestane. 
Nebo jinej case: Proklikam se na 3.4. -> Kliknu na Prev -> hodi me to o 2 zpet na Buckets

**Comment by ujovlado** [comment]
@janmichek ok, toto som skusil:

> Nasleduju vsechny instrukce, proklikam se k 2.5 -> kliknu Prev -> nic se nestane.

ked kliknem "Prev step", normalne mi to zmeni na 2.4.
![peek 2017-12-04 12-47](https://user-images.githubusercontent.com/419849/33551309-46d1c032-d8f1-11e7-99b4-3fc025fd01f9.gif)

malo by to podla teba spravit nieco ine?

**Comment by janmichek** [comment]
@ujovlado Myslim ze by se aplikace mela vratit na screen, ktery popisuju ve wizardu =  vyberu tabulek (/extractors/keboola.ex-db-snowflake/). Podobny pripad je na kroku 2.4. Kliknu na  Prev, ale aplikace me nevrati zpet na 'Setup credentials'. Predtim to teda tak fungovalo, ze to vracelo aplikaci na screen, ktery popisuji instrukce.

**Comment by janmichek** [comment]
Pridavam case: jsem na 5.4. -> Kliknu na Prev -> aplikace zustane na 'Configure Tasks'. OCekaval bych ze me veme na 'Orchestration Overview'

**Comment by ujovlado** [comment]
> Myslim ze by se aplikace mela vratit na screen, ktery popisuju ve wizardu = vyberu tabulek (/extractors/keboola.ex-db-snowflake/)

toto ale nie je mozne predsa, lebo aby si sa dostal na vyber tabuliek, musel by si zmazat tie existujuce

> Podobny pripad je na kroku 2.4. Kliknu na Prev, ale aplikace me nevrati zpet na 'Setup credentials'.

a tym padom mi nedava zmysel ani toto (aj ked tu by sa s tym asi nieco spravit dalo):

> Predtim to teda tak fungovalo, ze to vracelo aplikaci na screen, ktery popisuji instrukce.

imho nie, pretoze to by sa tie tabulky ozaj musel mazat

**Comment by janmichek** [comment]
ok, to prvni dava docela smysl co pises. Nerikam ze to musi fungovat stoprocentne stejne jako predtim.

Co jsem si ale jisty ze fungovalo jinak:
nasledujici case: Nasleduju instrukce az na 3.5 -> Klikam Prev, protoze jsem zapomel predchozi info -> ok zjisteno, chci pokracovat ve flow,
 Klikam na next -> uz se ale nedostanu na 3.5 pomoci Next. Viz gif 

![token error](https://user-images.githubusercontent.com/15363559/33555729-b216389a-d901-11e7-8df6-e4d477a35831.gif)

**Comment by ujovlado** [comment]
Mam uz fix, v tej L2 to spravim aspon tam kde to ide. Na L3 kuknem hned potom.

**Comment by ujovlado** [comment]
Oka, mam uz aj ten prechod z 3.5. na 3.4 (za chvilku pushnem) ... v niektorych pripadoch to ale nepojde (slo by ale museli by sme si pamatat dalsie veci v localStorage) ... takze napr. z 3.6 (jobs) sa po kliknuti na Prev nedostatnes na 3.5 (lebo si nepamatame config a row)

**Comment by ujovlado** [comment]
@janmichek kukni si potom ked tak #1351 , #1352  a #1353 , malo by to uz ficat vsetko. Tym padom davam od Guide mode ruky prec.

Toto co si pisal v tom tasku pre mna:

> Potom se rozjede navigace / routovani 

sa bude diat vzdy ked clovek pojde zo sekcie storage.
