### ISSUE TITLE
Upgrade to React 15

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1577]
Zacinaju sa nam pomaly zbierat issues, kvoli ktorym by sme mali updatnut.

@natocTo bolo by super, keby si to nejako zanalizoval a pozistoval, co vsetko treba urobit.

Len pre referenciu prikladam, ako sme to robili pri update na React 14: https://github.com/keboola/kbc-ui/pull/819

Announcement na React 15 je tu: https://reactjs.org/blog/2016/04/07/react-v15.html a vyzera to tak, ze tych Breaking Changes nie je moc: https://reactjs.org/blog/2016/04/07/react-v15.html#breaking-changes

Priebezne budeme updatovat tento popis o veci, ktore treba spravit:

- [x] Update samotneho `react` a `react-dom` (`yarn add react@^15 react-dom@^15`)
- [x] Update react-addons (css transition, pure render, test utils)
- [x] Update react-test-renderer, enzyme-adapter-react-15
- [x] Checknut co s nasim react-shim (mozno uz netreba data-keboolaid)
- [x] Direct call of PropTypes (napr. `PropTypes.shape()`) #3083
- [x] Direct call of React.createClasss
- [x] potom vyhodit custom fork react-datetime: https://github.com/keboola/kbc-ui/pull/2752
- [x] checknut docasne zakazane veci:
  - [x] prefetch plugin 38aa5e72383db375ce2f370479164dcc090eeed6 #3104
  - [x] no/deprecated 31333bae50b1f3f5dbd39e239042e1d3db6ed55d
  - deprecated warning ceb568af1513d8ce5a2e13087fbd8cb39ff3242b

Suvisiace, co sli do mastra:

- [x] Vyhodenie pouzitie "react dom factories" (ak ich bude neskor treba viac, pouzijeme libku) #3026
- [x] className typos #3013
- [x] vyhodenie `...props`:
  - [x] vseobecne #3015
  - [x] na react-select #3017 
- [x] Zbavit sa KbcBootstrap #3031
- [x] Use one root element in clipboard component #3027
- [x] Move static select options definitions out of createClass spec #3090

Myslim, ze niektore veci budeme vediet poslat do produkcie aj skor (napr. pouzitie `prop-types` alebo `create-react-class`). A zase niektore mozno ani nebudu nutne.

Idealne keby vznikol jeden WIP pull request, do ktoreho budeme mergovat ostatne - branch https://github.com/keboola/kbc-ui/tree/ujovlado-react-15.

**Comment by tomasfejfar** [comment]
> Idealne keby vznikol jeden WIP pull request, do ktoreho budeme mergovat ostatne.

Tenhle systém se moc neosvědčil na db-ex-v10 imho, jfyi ;) Tedy pokud to není práce na týden.

**Comment by ujovlado** [comment]
Preco sa neosvedcil? Ak si dobre spominam, presne takto sme updatovali na React 14 a slo.

**Comment by natocTo** [comment]
Toto si myslím bude rychlejší update než byl ten na React 0.14 těch, změn není tolik. A zase pak pomůže ten codemod apod určo.

@ujovlado asi blbost toto https://github.com/keboola/kbc-ui/pull/3003 přihodit k tomu updatu že. Ono to není nutné vůbec ale říkal jsem si lepší to mít aktuální před updatem. Tak spíš počkám pak rebasnu.

**Comment by ujovlado** [comment]
Jasne, to este mergnem predtym. Vsetko co moze ist do mastra skor sa posnazim dat tam skor. Aby bol vysledny diff co najmensi. Napr. tie prop-type budu moc ist skor imho. A mozno aj create-react-class. To sa vsetko uvidi za behu.

**Comment by ujovlado** [comment]
Codemod nam brutalne pomoze prave pri tych dvoch.

**Comment by natocTo** [comment]
jo to by bylo super, z "normálních" PR by bylo fajn ještě předem mít https://github.com/keboola/kbc-ui/pull/2329 protože tam vidím 28 souborů a bylo by určo kupa konfliktů, kdyby se pustily codemody předtím. Nebo se rozhodnout že se to nakonec nepoužije třeba. Plus ještě tento je kupa souborů https://github.com/keboola/kbc-ui/pull/2985 .. ale zase třeba by to šlo i pak v poho. Zase to bude upravovat ten codemod jinde. Horší by byl prettier nebo tak.

**Comment by natocTo** [comment]
Já teda začnu updatem nějakých knihoven, případně webpacku a věcí kolem testování a eslintu apod, aby šel program pustit. Ty dva codemody se můžou udělat bokem a pak na to navázat.

**Comment by tomasfejfar** [comment]
> Preco sa neosvedcil?

Protože ti vedle toho jede vývoj, který se nemůže zastavit a přišlo mi, že je potřeba hrozně moc backportovat a rebasovat. Chápu, že to nejde u BC breaků, které bez nového reactu nefungují, ale jinak bych řekl, že všechno ostatní by mělo rychle do masteru.

**Comment by ujovlado** [comment]
Jo, presne tak sme ro robili. Vsetko co mohlo slo hned do mastra. Ale viac sme to uz minimalizovat nemoholi. Rebasovalo sa to na dennej baze. Nakoniec tam ostalo ~150 commitov a preslo to bez vacsich problemov. A snazili sme sa aby boli hlavne zmeny v dependencies, nie v kode samotnom - cim sa dost eliminovali konflikty. Komponent sme sa (az na zmenu importov) nedotkli.

**Comment by ujovlado** [comment]
Ale bol to konsky diff, to ano: https://github.com/keboola/kbc-ui/pull/819/files. Tuna to bude, povedal by som, tak 5x menej narocne.

**Comment by natocTo** [comment]
U mě to jde jinak dobře. Když vypnu Eslit aby nehlásil deprecated věci (což hodně opraví ten codemod) a ještě jsem udělal pár úprav. Tak už testy komplet projdou, eslint tak a i se spustí dev. Build ještě otestuji. Myslím že tu první verzi nahodím už dnes. Jako ten úplnej základ.

**Comment by ujovlado** [comment]
Doplnil som tu branch do popisku (`ujovlado-react-15`)

**Comment by natocTo** [comment]
Ted mi React hlásí že tam mám props `classNmae` (typo) a vidím že to je dokonce na 10 místech v 7 souborech. To asi určo lepší opravit v jiném PR než házet sem že? Tu teda zatím opravovat kód minimálně.

**Comment by ujovlado** [comment]
Jj, to pojde separatne (tiez som si to vsimol), tak ako sme pisali vyssie, co moze ist do mastra hned, pojde hned.

**Comment by ujovlado** [comment]
@natocTo inac ak si povsimas tych veci viac, kludne to sem dumpni, mozeme si to aj porozdelovat.

**Comment by natocTo** [comment]
Jo teď jsem opravoval to první, tak uvidím kolik toho bude ale snad ne nějak extra. To kduž máš dovču tak ti nebudu házet navíc úkoly ne? :) Nebo by bylo super zkusit třeba ty codemody, pokud na to máš prostor. Nebo na to mám pak mrknout?

**Comment by natocTo** [comment]
Jinak třeba problematický je ten `Input` co je ve "common/bootstrap/Input", ale to vím že jsme chtěli celkově nějak vyhodit. Vůbec tam nejsou nějaký props definované (value, onChange), pak hodně se tam používá `{...this.props}` takže pak komponenty dostávají kupu props chtějí nepotřebují a React to nově hlásí.

**Comment by natocTo** [comment]
Na ten výskyt `{...props}` se podívám dnes. Toho asi bude více ale bude fajn to nemít. 

Ještě jsem se chtěl zeptat na toto: "Direct call of PropTypes (napr. PropTypes.shape())" s tím je jaký problém?

Jinak update nějakých knihoven už jsem dělal, i ten "react-datetime". Updatoval jsem jen věci kde nebylo potřeba pak v kódu nic měnit nebo jen úplné minimum. Myslím že mi tam pronikla i jedna knihovna mimo "react-*" ale pak už jsem se hlídal. Zkoušel jsem i build a neviděl jsem tam žádné varování ohledně peerDependencies nebo tak.

Ten "react-shim" tam byl kvůli tomu že třeba indigo-ui jelo na novějším Reactu? Zatím jsem to zachoval ale můžu to pak zkusit bez.

**Comment by natocTo** [comment]
react-shim koukám se používal kvůli Zendesku, jestli jsme to správně pochopil. Asi bych to tam zatím nechal, aspoň na první pokus pak se to ještě může otestovat.

Jinak jsem ještě nahradil ten addon na transition a přešel nejdrív na v1 té nové knihovny (drop-in-replace) a pak update na v2 a vypadá to ok.

Zkoušel jsem update `react-hot-loader` a vše vypadalo ok ale prostě to nefungovalo tak dobře jako ten starší, nevím proč, daleko často to dělalo reload. Skoro vždy vlastně pokud jsem to měl napojený hned na `App.jsx`, pokud někde níže tak tam to už běhalo líp. Chvilku jsme to zkoumal ale nakonec jsem nahodil zpět tu verzi co tam byla do teď, tak zatím funguje hezky.

Ty chceš nejdřív udělat ty codemody a až pak update reactu nebo to může být i naopak?

Ještě jsem přemýšlel že zkusím vyhodit "immutable-render-mixin" a všude kde je použiji "pure-render-mixin". Abych kouknul co to vlastně udělá. Myslím že by měl stačit pouze ten jeden.

**Comment by natocTo** [comment]
Čtu si o tom Prefetch pluginu. Jsem myslel že to nějak ovlivní načtení webu nebo výkon aplikace a ono to slouží asi nějak k optimalizaci buildu "jen". Ani nikde nevidím nějaký příklad kde by to bylo použito s Reactem takto. Možná by se to tam nemuselo vracet. O nastavení méně. Co myslíš?

https://webpack.js.org/plugins/prefetch-plugin/
https://stackoverflow.com/questions/32923085/how-to-optimize-webpacks-build-time-using-prefetchplugin-analyse-tool

**Comment by natocTo** [comment]
K něm `prop-types` a `createClass` budeš teda ještě něco dopisovat? Zítra bych se na to asi vrhnul.

**Comment by ujovlado** [comment]
Aha, vidis, to mi uslo. Ja som to vlastne len chcel skusit, je mozne, ze nieco z toho mozeme dat do mastra skor. Vyskusam a napisem sem.

**Comment by natocTo** [comment]
- `prop-types` šlo OK

- `createClass` zkouším na jedné složce a myslím že to bude taky ok (pustim to celé až bude to první v masteru), tam chceme všude použít rovnou `createReactClass` nebo pustíme celou tu "class" transformaci? Ta tam má kupa dalších úprav a upravuje komponenty i na ES6 Class pokud to jde, což je super. Tam kde máme `immutableRenderMixin` to převádět teda nebude, na to ještě mrknu

**Comment by natocTo** [comment]
@ujovlado nezkusíme to dotáhnout dnes? Nebo nevím zda není špatný to překlopit v pátek, ale nemělo by to být problém.

- react-shim - to bych klidně prozatím nechal jak je, to se může zkusit zahodit po updatu - tam to má co dělat ze Zendeskem (aspoň původní info), tak nevím moc jak to testovatl
- PropTypes a ReactClass - jedno je, druhé jsme testoval a překlopil to v poho snad
- ty deprecated hlášky by se mohli vyhodit snad, tam už to nic jiného nehlásilo myslím, by se otestovalo
- prefetch plugin mrknu

Ty props se včera vyřešily, tak to je asi vše.
Klidně bych k tomu ještě připojil update té Sentry. Ať to mám "komplet" nové :)

**Comment by natocTo** [comment]
Jo ten prefetch jsem vlastně zkoumal, viz https://github.com/keboola/kbc-ui/issues/1577#issuecomment-470245925 .
To si myslím že by se také nemuselo znovu používat. Nebo udělat nějaké test před po a zkusil několik buildů, ale nečekám tam nějaký veliký časový rozdíl.

**Comment by ujovlado** [comment]
Asi mozeme, pozriem tie PR a uvidime :)

**Comment by natocTo** [comment]
Super, propTypes jdu ještě mrknou a rebasnout. Ty createClass bych stavěl až pak na tom.

**Comment by natocTo** [comment]
Ještě jsem tu připojil tento PR https://github.com/keboola/kbc-ui/pull/3090
To bych taky ještě zkontroloval/nahodil než se pustí ten codemod na createClass.

**Comment by ujovlado** [comment]
Rozmyslam este co s tym React.createClass. Ci by sme to nevedeli nejako najprv skonvertovat vsetko na `createReactClass`. Lebo ked to spustim len tak (bez options), mam tam teda toho hodne.

**Comment by ujovlado** [comment]
Na druhu stranu, `createReactClass` potrebujeme len kvoli "legacy" mixinom.

**Comment by natocTo** [comment]
Nevím jestli tam na to je options, ale to by šlo i nějaký "search+replace". Ale pokud se to udělá přes codemod a projdou testy apod tak by to bylo asi lepší. I je to testovaný facebookem tak by to mělo být OK. Podle mě tam bude kupa kontrola před tím než se to převede na Class.

Hodně komponent kde mám "immutableMixin" to taky nebude převádět, to by se pak muselo nějak upravit na "HoC" nebo dekorátor.

**Comment by ujovlado** [comment]
Ten immutable render mixin by som najradsej poslal do prdele :-D

**Comment by natocTo** [comment]
To jsem zkoušel a nedopadlo to moc dobře. :) Jak máme často ten edit stav ve storu.

**Comment by ujovlado** [comment]
OK, myslim, ze takto je to schodne:

```
jscodeshift -t react-codemod/transforms/class.js --display-name=false --conversion=false --extensions=js,jsx src/scripts/
```

**Comment by natocTo** [comment]
Jo tak asi máš pravda, takto ten diff vypadá bezpečně. Tak to rovnou pošleš jako PR? Ještě teda nainstalovat tu knihovnu ale to je jasný.

**Comment by ujovlado** [comment]
Otazka ale ci to chceme riesit, ono to vyhadzuju az v 16ke. Ale zase bolo by fajn nemat tam warningy.

**Comment by natocTo** [comment]
Bych to použil rovnou. Takto ta změna není veliká.

**Comment by ujovlado** [comment]
ok, poslem PR, mam to tu

**Comment by natocTo** [comment]
Ok, pak rebasnu ten final PR, zkusím vyhodit ty eslinty atd a uvidíme jak to pojede

**Comment by ujovlado** [comment]
No este to chvilku potrva, mi tam hodilo vela false-positives (ked je napr. ta komponenta funkcia). Este to kuknem.

**Comment by ujovlado** [comment]
Skusal som to bez `PrefetchPlugin` a nevidim ziadny rozdiel. Ak by sa vyskytol problem, budeme to riesit. Kazdopadne produkcny build sa nebude lisit. Marknem to ako solved.

**Comment by natocTo** [comment]
Tady jsem právě dohledal přimo Martina jak řeší ten "shim" a bylo to něco kolem Zendesku.

https://github.com/facebook/react/issues/1939#issuecomment-138282459

**Comment by ujovlado** [comment]
ten shim skusim vyhodit, regnem si to do connection a uvidime

**Comment by ujovlado** [comment]
lebo ak to spravne chapem, od React 14 by to uz nemalo byt potrebne.

**Comment by ujovlado** [comment]
Ten zendesk widget sa tam generuje do iframe, nenarazil som na problem po tom, co som vyhodil ten custom data attribute. Poslem PR.

**Comment by ujovlado** [comment]
No ak spravne kukam uz tam je len ta vec s warningami ...

**Comment by natocTo** [comment]
Jo no. To moc nevím jak vyřešit aby to šlo vyhodit.

**Comment by ujovlado** [comment]
Este mi napada, ci by sa neoplatilo updatovat ten react router, na nejaku verziu, co podporuje uz React 15, a nepouziva tie stare veci.

**Comment by natocTo** [comment]
To mě napadlo taky no, ale myslím že je to docela komplikované, že ta verze 0.13 se už od 1 dost liší. A asi ani to by nepomohlo, teď je už verze 4 a před pár dny dokonce vyšla snad 5ka.

Co jsem koukal tak ta 0.13 je taková fajn jak konfiguruješ hezky přes obyčejný objekt. Že ty další verze už to takto nemají, nebo s tím máš nějakou zkušenost jinou?

**Comment by ujovlado** [comment]
V developer-portal-ui sme nieco skusali, no ja som tam nakoniec hodil `found` router.

https://github.com/reacttraining/react-router/tree/master/packages/react-router-config#route-configuration-shape

**Comment by natocTo** [comment]
Zkusil jsem připravit nějakou verzi které více sedí na React 15. 

Udělal jsem issue na "react-router" něco jako v0.14 ale to samo neprošlo a už je to zavřené. Nejdřív jsem si teda udělal fork a udělal klasický update "create-react-class", "prop-types" a nějaký menší úpravy o volání propTypes jako funkce apod. Všechny testy prošly (dva jsem teda trošku upravil, ale to byla drobnost).

Když si ale natáhnu daný fork, tak to furt nefunguje, ale už z jiného důvodu. Tam se nepracuje s novým buildem ale přímo se zdrojovým kódem a ten asi není kompatibilní, nevím nezkoumal jsem to do detailu.

Tak jen abych zkusil zda to bude fungovat musel jsem to publishovat na npm pod novým název. React-router má MIT licenci tak by to mělo být v poho.

https://www.npmjs.com/package/r15-happy-router

Jakože React 15 happy router - nestěžuje si na ty deprecated věci. S tímto pak už router pracuje OK, nicméně zjištuji nově že to nestačí. Teď mi to hlásí stejnou věc u "react-code-mirror". Ti mají novou verzi která by to mohla vyřešit, ale nevím zda nebude pak na řadě další knihovna.

Pokud by ten router byl takto dobrý, tak asi lepší to hodit pod keboolu.
Ten form je tu: https://github.com/natocTo/react-router - já tam zkoušel nějaký tagy atd zbytečný, nemám s tím moc zkušenosti, ale šlo by z toho vybrat i jen ty úpravy.

**Comment by natocTo** [comment]
Změny jsou jen ty základní:
https://github.com/natocTo/react-router/commit/b132c7715a704e2e78d377444185f2fc79444b06

Plus nějaká "PropTypes.checkPropTypes" jsem musel použít + ty dva testy pidi aktualizovat.
