### ISSUE TITLE
Badges tunning [master issue]

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1737]
Sesypavam tasky ohledne uprav pro Badges. Domnivam se ze je to vsechno co jsme si rekli

- [x] https://github.com/keboola/kbc-ui/issues/1723
- [x] https://github.com/keboola/kbc-ui/issues/1736
- [x] https://github.com/keboola/kbc-ui/issues/1735
- [ ] https://github.com/keboola/kbc-ui/issues/1734

**Comment by janmichek** [comment]
All done, upravil jsem dle  instrukci.
Nove pribyly badges tady

![image](https://user-images.githubusercontent.com/15363559/40732088-d5c2e380-6432-11e8-8524-2bf580542df1.png)
