### ISSUE TITLE
User feedbacks easy fixes [master issue]

### ISSUE THREAD

**Issue by janmichek** [keboola/kbc-ui#1961]
Seznam issue ktery vychazi z uzivatelskeho povidani.
Tyhle veci jsme ohodnotili jako malo prace - hodne uzivatelskeho pohodli
- [x] Feature request option https://github.com/keboola/kbc-ui/issues/1960
- [x] Disable individual transformations #1966 
- [x] Retry job tuning https://github.com/keboola/kbc-ui/issues/1964
- [ ] Show Credit spent https://github.com/keboola/kbc-ui/issues/1965
- [ ] More project power information https://github.com/keboola/syrup-queue/issues/76
- [ ] Responsive subpages https://github.com/keboola/kbc-ui/issues/1963
- [ ] Show incremental label per table https://github.com/keboola/kbc-ui/issues/1967
- [ ] vytvorit issues z dalsich feedbacku [ktere maji uz ale vyssi cenovku] https://docs.google.com/spreadsheets/d/1vNh1t5OMp18u9v5JRO17RFwAsQaysbvOtVLHlrHMSFw/edit#gid=0
- [ ] popremyslet o dalsim kolecku user feedbacku. Zamerit se spis na novacky
