### ISSUE TITLE
Project Graph - shippable v1

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#3069]
Related: #2875

Tasky:

- [x] Init project graph #3066
- [x] Pripravit project/overview v connection https://github.com/keboola/connection/issues/1871
- [x] Pridat graph.keboola.com do services https://github.com/keboola/connection/issues/1873
- [x] ~Najst nejaku kniznicu na graf (alebo pozriet, co uz mame a ci sa to da pouzit)~ // ostalo co mame
- [x] Vyhodit proxy, ked sa pridaju potrebne hlavicky https://github.com/keboola/kbc-ui/commit/e3c07b4dd943cb0188e446088a406f317a5e3561
- [x] Odkazy zo zonamu projektov v organizacii https://github.com/keboola/connection/issues/1944
---

Zatial som si to predstavoval takto:

-  komponenta ProjectGraph sa neskor vyexportuje do `parts`, a potom by sa jej predal len token
- v `componentDidMount` by si dotiahla vsetky data

Co tam nie je doriesene:

- aka graph kniznica sa pouzije
- renderovanie lineage (to sa asi bude musiet splachnut manualne)

Namiesto toho jsonu, co tam teraz je by asi mal byt nazov projektu a potom ta komponenta, kde uz budu taby, kde sa da prepinat medzi lineage/graph.

**Comment by ujovlado** [comment]
@natocTo toto na ten backend necaka, moze sa na tom zacat robit. Tie veci na connection, co spominam vyssie su skor kvoli tomu, ked to budeme chciet dostat do produkcie.

Inac by normalne malo ficat `yarn start-project-graph`.

Tam si asi len daj pozor, ze tam nie su dostupne stores a pod. je to vlastne len "suche" vyrenderovanie, cez `ReactDOM.render`

**Comment by natocTo** [comment]
Ok, zrovna na to jsem se chtěl zeptat.

**Comment by ujovlado** [comment]
Toto tu zavrem, je to vlastne ready.
