### ISSUE TITLE
DB extractor and DB schema

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui#3105]
Pokud je v DB hodně tabulek a schémat, je výběr z existujícího selectoru peklo - chtělo by to nějakej větší modal, kde se zaškrtá víc tabulek nebo může vyhledávat. Když se dělá první konfigurace po zadání credentials, chtělo by to checkboxy na list tabulek + nějakej funkční search.

Když se pak přidává jen jedna nová konfigurace, chtělo by to při použití searche vidět SCHEMA tabulky, které teď zmizí.

A jakmile se to nastaví, chtělo by to vidět jméno schematu už na úrovni jména konfigu. Trápí mě to dlouho (od doby DPD loni na jaře) a teď to doputovalo jako schnilá brambora i ke klientovi do týmu. Popisují to tady: https://keboola.zendesk.com/agent/tickets/9986

Zvládli bysme nějakej quick fix co nevyžaduje full-size loop přes UX designera (Kariho)?

---

- [x] schema v detaile query (#3149)
- [x] schema+tabulka na zozname queries (#3154)
- [x] schema+tabulka v siebare (podobne ako index) (#3156)
- [x] moznost vybrat viac tabuliek naraz (#3108)
- ~vyhladavanie aj v schema a schema.table?~ v dalsom PR ked tak

**Comment by pivnicek** [comment]
treba duplicate? https://github.com/keboola/kbc-ui/issues/2229

**Comment by ujovlado** [comment]
Viem, ze si to uz raz reportoval, a dokonca bol mozno na to PR. Ale neviem ako to dopadlo. Kukneme sa na to.

**Comment by ujovlado** [comment]
Takze ano, nejaky quicfix vymyslime. Ale zase nie tak quick aby to bol fail :)

**Comment by padak** [comment]
@pivnicek not clear duplicate, but related to definitely! thanks for linking it!

**Comment by ujovlado** [comment]
Idem sa na to pozrit viac, mam chvilku cas.

**Comment by natocTo** [comment]
Jedno PR jsem k tomu posílal, neřeší vše ale třeba bude užitečné.
https://github.com/keboola/kbc-ui/pull/3108

**Comment by ujovlado** [comment]
Rozdelime to na viac PRs, ako Jakub naznacil v #3108:

> Pokud je v DB hodně tabulek a schémat, je výběr z existujícího selectoru peklo - chtělo by to nějakej větší modal, kde se zaškrtá víc tabulek nebo může vyhledávat. Když se dělá první konfigurace po zadání credentials, chtělo by to checkboxy na list tabulek + nějakej funkční search. 

> Když se pak přidává jen jedna nová konfigurace, chtělo by to při použití searche vidět SCHEMA tabulky, které teď zmizí.

> A jakmile se to nastaví, chtělo by to vidět jméno schematu už na úrovni jména konfigu.

**Comment by ujovlado** [comment]
Ten index by teda mohol by porieseny ako spominam v #3154

**Comment by ujovlado** [comment]
No a potom este sidebar, ktory by (podla indexu z #3154) mal vyzerat cca takto:

![Screenshot 2019-03-28 at 16 21 01](https://user-images.githubusercontent.com/419849/55169682-7f489f00-5175-11e9-84c8-18d9c6c0457c.png)

**Comment by ujovlado** [comment]
A posledny fine-tuning by bol, ze to bude v tableName a schema aj vyhladavat.

**Comment by pivnicek** [comment]
sidebar looks great!  I would keep the `source:` label even for the SQL badge though

**Comment by ujovlado** [comment]
Tu sme myslim poriesili vsetko. Ak by nas palil ten search, tak potom v inom PR, ako som pisal vyssie.
