### ISSUE TITLE
Replace usages of ModalTrigger by Modal

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#826]
- https://github.com/react-bootstrap/react-bootstrap/blob/v0.23.7/src/ModalTrigger.js#L109
- `ModalTrigger` is deprecated (already in current version of `react-bootstrap`)
- Repacing its usages will help migration to new React, since proxy modules won't be necessary for it
- PR fixing this should go to `master` branch
- Files bellow contain `ModalTrigger`

Parts:
- [x] Part 1. - tde ex, wr dropbox  #828
  - [x] src/scripts/modules/tde-exporter/react/pages/Index/TableRow.coffee
  - [x] src/scripts/modules/tde-exporter/react/pages/Destination/DropboxRow.coffee
  - [x] src/scripts/modules/wr-dropbox/react/pages/index/Index.coffee
  - [x] src/scripts/modules/ex-dropbox/react/Index.jsx
- [x] Part 2. - orchestrations #840
  - [x] src/scripts/modules/orchestrations/react/components/OrchestrationTaskRunButton.jsx
  - [x] src/scripts/modules/orchestrations/react/components/OrchestrationRunButton.jsx
  - [x] src/scripts/modules/orchestrations/react/components/JobRetryButton.coffee
  - [x] src/scripts/modules/orchestrations/react/components/NewOrchestionButton.coffee
  - [x] src/scripts/modules/orchestrations/react/pages/orchestration-detail/OrchestrationDetail.coffee
  - [x] src/scripts/modules/orchestrations/react/pages/orchestration-tasks/TasksEditor.coffee
  - [x] src/scripts/modules/orchestrations/react/pages/orchestration-tasks/TasksEditTableRow.coffee
  - [x] src/scripts/modules/orchestrations/react/pages/orchestration-tasks/TasksTableRow.coffee
- [x] Part 3. - transformations #846
  - [x] src/scripts/modules/transformations/react/components/NewTransformationBucketButton.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformation-bucket/TransformationBucket.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformations-index/TransformationBucketRow.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/Phase.jsx
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/AddInputMapping.jsx
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/TransformationDetailStatic.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/InputMappingRow.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/TransformationDetail.coffee
  - [x] src/scripts/modules/transformations/react/pages/transformation-detail/AddOutputMapping.jsx
  - [x] src/scripts/modules/transformations/react/modals/SqlDepModalTrigger.coffee
- [x] Part 4. - generic/common components #874 
  - [x] src/scripts/modules/components/react/components/generic/FileOutputMappingHeader.coffee
  - [x] src/scripts/modules/components/react/components/generic/TableInputMappingHeader.coffee
  - [x] src/scripts/modules/components/react/components/generic/AddFileOutputMapping.jsx
  - [x] src/scripts/modules/components/react/components/generic/AddTableOutputMapping.jsx
  - [x] src/scripts/modules/components/react/components/generic/AddFileInputMapping.jsx
  - [x] src/scripts/modules/components/react/components/generic/FileInputMappingHeader.coffee
  - [x] src/scripts/modules/components/react/components/generic/TableOutputMappingHeader.coffee
  - [x] src/scripts/modules/components/react/components/generic/AddTableInputMapping.jsx
  - [x] src/scripts/modules/components/react/components/RunComponentButton.jsx
  - [x] src/scripts/react/common/Confirm.jsx
  - [x] gooddata writer ui - rozjebany menu bar vpravo
- [x] Part 5. - ex gdrive old, gooddata wr, ex analytics #850
  - [x] src/scripts/modules/gooddata-writer/react/components/TableLoadType.coffee
  - [x] src/scripts/modules/gooddata-writer/react/pages/table/DatasetColumnEditorRow.coffee
  - [x] src/scripts/modules/ex-google-analytics/react/pages/index/Index.coffee
  - [x] src/scripts/modules/ex-google-drive-old/react/components/RunExtraction.coffee

**Comment by ujovlado** [comment]
:tada:
